### ISSUE TITLE
2023년 2월 채용 공고 자사 사이트 업로드

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#123]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.
- 2023년 2월 채용 공고 업로드

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.
- 2023년 2월 채용 공고가 필요합니다

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.
- @T-Mook 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] 채용 공고 페이지 생성
  - [x] 공고 내용 입력
  - [x] deploy

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: https://github.com/knowease-inc/Business-Strategies/issues/176
  - 참고사항
    - [당근마켓 채용](https://team.daangn.com/jobs/)

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @T-Mook 
  - Domain  : **Business**
  - Priority: **High**
  - Task    : **Documentation**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by tooget** [comment]
링크드인 채용 무료 1건 이용 추천합니다.

**Comment by T-Mook** [comment]
# 재오픈
- 사유 : bugfix 필요
- 문제
   - [ ] 회사 로고 표시가 되어야함
   - [ ] 채용 화면으로 가는 메뉴 추가 필요

**Comment by T-Mook** [comment]
## 내용 업데이트
- 외부인의 시각에서 본 추가 코멘트가 있었음!
- 참조. [웹개발자(frontend, 경력) 채용 공고_202302.pdf](https://github.com/knowease-inc/knowease-inc.github.io/files/10664818/frontend._202302.pdf)
   - 유연 근무 가능, 100% 재택 근무 등의 강점 강조
   - 가능하다면(?) 경력 단절 등 기타 '지원자 스스로 생각했을 때 약점이라고 생각할 수 있는 부분도 역량만 되면 약점이 되지 않는 곳'이란 어필
