### ISSUE TITLE
신규 입사자 링크드인 게재 (2023.5)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#131]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.
- 신규 입사자 링크드인 게재 완료

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.
- 신규 입사자 발생

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.
- @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] 로컬 구동 성공
     - [x] git template 사용
     - [x] 구동 성공
  - [x] 링크드인 가입
  - [x] 링크드인 badge url
  - [x] 삽입 방법 학습
  - [x] 삽입
  - [x] 로컬상 확인
  - [ ] 배포
     - [x] branch 구분
     - [x] push 동작 확인
     - [x] Pull reqeusts

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: https://github.com/knowease-inc/Business-Strategies/issues/232
  - 참고사항
    - https://tpdud406.github.io/SeYoung.github.io/

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @T-Mook 
  - Domain  : **Business**
  - Priority: **High**
  - Task    : **Documentation**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by tpdud406** [comment]
로컬 구동시 에러 발생
git clone 후 yarn dev시 아래 캡처본과 같은 에러 발생

- 확인한 에러 사유
nuxt2에 대응되는 node 버전이 최신 버전(20.x.x)도, 최신 LTS버전(18.x.x)도 맞지 않아서 발생

- 해결 방안
16.x.x대 node (lts) 버전 설치 및 적용

- 에러 내용
![스크린샷 2023-05-12 오전 12 19 35](https://github.com/knowease-inc/knowease-inc.github.io/assets/95858555/178dc05d-769f-4f7e-a6ca-0bec38d7fd87)

- 해당 에러 관련 github 이슈 발생건
[Nuxt2 default setup doesn't work with latest node LTS version 18.12.1 ](https://github.com/nuxt/nuxt/issues/10844)

**Comment by tpdud406** [comment]
@T-Mook 

현재 링크드인 뱃지 삽입 완료하였는데(로컬), 뱃지들 배치를 어떻게 하면 좋을지 궁금합니다~
1. 캡처본과 같이 3 / 1 (-> 이렇게 한다면 2번째 줄의 좌, 우, 중간 어디로 하면 좋을지)
2. 열 맞춰서 2 / 2

![스크린샷 2023-05-12 오전 10 08 15](https://github.com/knowease-inc/knowease-inc.github.io/assets/95858555/d7f7e76d-8323-4ef2-a866-0ba4d12095df)

**Comment by T-Mook** [comment]
우선 2/2 로 하죠!

@tpdud406

**Comment by tpdud406** [comment]
2/2로 진행하니 레이아웃이 좀 달라져서 아래 캡처본에 표시해둔 것처럼 변경한 후 어떤 것이 좋을지 여쭤보려고 했는데 생각대로 진행이 되지 않아 일단 2/2로 레이아웃만 변경하고, 추후에 추가 레이아웃 변경 필요시 적용할 수 있도록 방법 미리 찾아보겠습니다...!

1. 링크 텍스트 가운데 정렬 (desktop 기준)
![스크린샷 2023-05-12 오후 4 34 18](https://github.com/knowease-inc/knowease-inc.github.io/assets/95858555/85e03f20-28d7-4da6-8f54-951dcb07188f)

2. card 자체 가운데 정렬 및 링크 텍스트 카드 좌측 또는 상단에 가운데 정렬(mobile 기준)
![스크린샷 2023-05-12 오후 4 36 18](https://github.com/knowease-inc/knowease-inc.github.io/assets/95858555/7b8e7098-2bc1-43be-b239-c357a2cc989a)

**Comment by tpdud406** [comment]
@T-Mook
해당 이슈에 해당하는 내용 PR 올렸습니다.
확인 부탁드립니다~!

**Comment by tpdud406** [comment]
링크드인 뱃지 생성, 삽입 방법에 대한 참고 자료

https://www.makeuseof.com/how-to-add-linkedin-profile-badge-blog-resume-website/
