### ISSUE TITLE
신규 디자인 적용 (2023)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#154]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.
- 신규 디자인 적용 완료

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.
- 일부 페이지에 대한 신규 디자인 적용 필요

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.
- @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] 디자인 적용: 비즈니스상 주요 페이지만 우선 적용
     - [x] 회사 소개
        - [x]  웹
        - [x]  모바일
     - [x] 서비스 소개
        - [x]  웹
        - [x]  모바일

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: https://github.com/knowease-inc/MEANIIT-frontend/issues/134
  - 참고사항
    - 전체 페이지 디자인 적용이 아닙니다
    - **텍스트(font, 자간 등이 아닌 글[내용]의 길이에 의한 문제)에 의한 디자인 주안점은 생각하지 말고** 그 외 디자인만 신경써주시기 바랍니다
       - 이유: 서비스가 본질적으로 변경되며, 강조해야하는 내용이 변경되었으므로 디자인은 변경하되, '텍스트(내용)'는 대부분 변경될 예정이기 때문입니다

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W+**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @T-Mook 
  - Domain  : **Business**
  - Priority: **Medium**
  - Task    : **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by T-Mook** [comment]
@tpdud406 

#### 한 번에 여러 이슈가 등록되었으므로, 우선순위를 정리해드리자면
1. https://github.com/knowease-inc/MEANIIT-frontend/issues/159
2. https://github.com/knowease-inc/MEANIIT-frontend/issues/154
3. 본 이슈 (2번 이슈가 상당히 길어질 것으로 예상되는 경우에는 본 이슈를 우선 진행해주시는 것도 방법입니다)

참고하시길 바랍니다

**Comment by tpdud406** [comment]
@T-Mook 

작업 완료했습니다!

- 문제: 현재 `introdue.vue`페이지 모바일 버전에서 간헐적으로 깨짐 현상이 있습니다(`<html>` 전체가 좌측으로 치우침)
- 원인: 못 찾음(문제가 발생한 구간은 `introdue.vue`와 `index.vue` 각 페이지의 구성이 동일한데 차이 발생)
  <img width="374" alt="스크린샷 2023-12-26 오후 4 53 01" src="https://github.com/knowease-inc/knowease-inc.github.io/assets/95858555/d5feaa20-6596-460a-b3dc-6e87de0e1269">


- PR 남길까요?

**Comment by T-Mook** [comment]
@tpdud406 넵, PR 남겨주세요
