### ISSUE TITLE
신규 입사자 링크드인 게재 (2024.2)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#172]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.
- 신규 입사자 링크드인 게재 완료

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.
- 신규 입사자 발생

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.
- @jina5 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] 정보 취합
     - [x] 링크드인 가입: @jina5 
     - [x] 링크드인 badge url 제공 (코멘트로 작성): @jina5 
     - [x] Assignees 전환: @jina5 -> @tpdud406 
  - [x] 해당 url 이용 삽입: @tpdud406 (이하 @tpdud406 진행)
  - [x] 로컬 확인
  - [x] 그 외
     - [x] 모바일에서 프로필의 그래픽 + 텍스트 겹침 현상 확인 및 해결
  - [ ] 배포

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: #131
  - 참고사항
    - 링크드인 뱃지 URL 예시: `'<div class="LI-profile-badge" data-version="v1" data-size="medium" data-locale="ko_KR" data-type="vertical" data-theme="light" data-vanity="성묵-박-34a0a2135"><a class="LI-simple-link" href=\'https://kr.linkedin.com/in/%EC%84%B1%EB%AC%B5-%EB%B0%95-34a0a2135?trk=profile-badge\'>박성묵</a></div>'`

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @T-Mook 
  - Domain  : **Business**
  - Priority: **High**
  - Task    : **Documentation**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by jina5** [comment]
@T-Mook 헉 이거 알람을 못보고 이제야 확인했습니다 😱 

<div class="badge-base LI-profile-badge" data-locale="ko_KR" data-size="medium" data-theme="light" data-type="HORIZONTAL" data-vanity="jina5" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://kr.linkedin.com/in/jina5?trk=profile-badge">오지나</a></div>
              
뱃지는 스몰(기본) 맞을까요?

@tpdud406 안녕하세요 🙇 assignee 전환 하겠습니다. 잘 부탁드립니다~!

**Comment by T-Mook** [comment]
@tpdud406 

- 모바일에서 봤을 때 이미지 + 글자 겹침 현상이 링크드인측 문제로 이쪽에서 손 쓸 수 없다면
- 일단 넘어가는 걸로 말씀주세요!
