### ISSUE TITLE
서비스 소개 페이지 연혁 추가: 2024.4 파일럿 프로그램 진행

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#182]
# :sparkles: Feature Request

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

 - 서비스 소개 페이지 연혁에 '2024.4 파일럿 프로그램 진행' 추가

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 현재 진행되었던 내용에 대한 추가 필요

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 서비스 소개 페이지 연혁 추가
     - 연혁 이름: '2024.4 파일럿 프로그램 진행'
     - 연혁 내용 예시: 증권업 마케팅 부문, 화장품 제조업 상품기획 실무용 트렌드 브리핑 작성 AI 테스트 참여 제공 및 서비스 개선 실시
        - 문장, 배치상 부자연스러운 부문 발견 시 수정
  - [x] 회사 소개 페이지 연혁 추가
     - 연혁 이름: '2024.4 미닛 파일럿 프로그램 진행'
     - 연혁 내용 예시: 서비스 소개와 같음

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - https://github.com/knowease-inc/Business-Strategies/issues/302
    - https://github.com/knowease-inc/Business-Strategies/issues/300
    - https://github.com/knowease-inc/Business-Strategies/issues/303
  - 참고문서 URL, 스크린샷 등
    - TBD

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :airplane: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)

  - Reporter: @T-Mook 
  - Domain  : :briefcase: **Business**
  - Priority: :orange_square: **High**
  - Task    : :rocket: **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by tpdud406** [comment]
@T-Mook 

- 확인 부탁드립니다~

___

### 회사 소개 페이지 연혁
<img width="200" alt="스크린샷 2024-09-12 오전 9 20 39" src="https://github.com/user-attachments/assets/7dd4eaaa-379d-447b-9d2f-0fee00353684">

<img width="400" alt="스크린샷 2024-09-12 오전 9 20 49" src="https://github.com/user-attachments/assets/9919694c-a02d-4c68-89c4-c00ffa88cc9d">

### 서비스 페이지 연혁
<img width="200" alt="스크린샷 2024-09-12 오전 9 21 08" src="https://github.com/user-attachments/assets/bf03c871-aaaf-44aa-a3b5-cb6eefac3a23">
<img width="400" alt="스크린샷 2024-09-12 오전 9 21 14" src="https://github.com/user-attachments/assets/f8d05a89-8d1a-47de-8d8e-8ecbc2139339">

**Comment by T-Mook** [comment]
@tpdud406 

- 코멘트 변경 요청
   - 수정 전 : 증권업 마케팅 부문, 화장품 제조업 상품기획 실무용 트렌드 브리핑 작성 AI 테스트 참여 제공 및 서비스 개선 실시
   - 수정 후 : 상장/대기업 실무자 대상 맞춤형 트렌드 브리핑 작성 AI 테스트 참여 제공 및 AI 개선 실시

**Comment by T-Mook** [comment]
수정후 PR 올려주세요~
