### ISSUE TITLE
링크드인 이미지 에러 해결(2)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#183]
# :lady_beetle: Bug Report

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

 - 특정 임직원의 프로필 사진 에러없이 출력

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 특정 임직원의 프로필 사진 출력 에러

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 원인파악
  - [ ] 문제해결
     - 링크드인 URL을 사용하는 것으로 앞으로도 이 에러가 계속 반복될것 같다면, 아예 프로필 이미지를 다운받아서 FE에서 static에 이미지 담아서 사용하는 방식으로 해결해주세요.

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - #174, https://github.com/knowease-inc/MEANIIT-backend-for-researcher-ECS/pull/235#issuecomment-2329353875
  - 참고문서 URL, 스크린샷 등
    - 현재 상태
       ![화면 캡처 2024-09-05 091817](https://github.com/user-attachments/assets/c81ae145-79af-48e5-aab3-404015c73c2d)

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 **한가지만** 선택해주세요.
> (1W- 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :airplane: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain을 **한가지만** 선택해주세요.
> (UX 가 아닌 경우 Domain 레이블을 변경해주세요.)

  - Reporter: @jina5 
  - Task    : :lady_beetle: **Bug**
  - Priority: :red_square: **High**
  - Domain  : :iphone: **Business** 

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by tpdud406** [comment]
일부 임직원의 LinkedIn 프로필 이미지의 URL이 자주 변경되는 이유

### 원인
- 최근 몇 년 동안 LinkedIn은 개인정보 보호와 보안 강화를 위해 여러 정책을 변경

   - 과거: 사용자 프로필 이미지를 고정된 URL로 제공
   - 현재: 프로필 이미지 URL 동적 생성(URL이 시간이 지나면 만료 또는 변경되도록 하여, 외부에서 직접적으로 이미지를 참조하지 못하도록 조치)
   - 대안: 1. LinkedIn API 사용: 사용자 인증(OAuth) 필요, 설정 복잡, 제한 있을 수 있음
            : 2. 이미지 수동 관리: 프로필 이미지를 다운로드하여 서버에 업로드해 고정된 URL로 제공.


### 처리 방안
- 앞으로도 계속 이와 같은 에러가 발생할 것으로 판단, 말씀하신 대로 'static' 폴더에 이미지 파일 아예 저장해서 사용하겠습니다!

**Comment by T-Mook** [comment]
@tpdud406 

- 사이즈 변동에도 원하는 위치에 원하는 이미지만큼 출력되는지 확인 해주시고 문제 없다면 PR 올려주세요.
