### ISSUE TITLE
고객사 컴포넌트 추가, 회사 소개 페이지 고객사 CI 추가 (6개)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#188]
# :sparkles: Feature Request

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

 - 회사 소개 페이지 내 고객사 컴포넌트 추가
 - 회사 소개 페이지 고객사 CI 추가 (6개)

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 고객사 표시 위치가 없습니다

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 고객사 컴포넌트 위치 잡기
     - [x] 타 스타트업 고객사 출력 위치 참고
     - [x] 컴포넌트 제작
  - [x] CI 확보 및 고객사 내 추가: 각 공식 홈페이지에서 CI 확보
     - [x] 경기도과학진흥원
     - [x] 성균관대학교
     - [x] 차 의과대학교
     - [x] 경민대학교
     - [x] 연성대학교
     - [x] ~소상공인시장진흥공단~ 나중에 (by. @T-Mook )
     - [x] CI 확인: @T-Mook 

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - https://github.com/knowease-inc/Business-Strategies/issues/309
  - 참고문서 URL, 스크린샷 등
    - TBD

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :airplane: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)

  - Reporter: @T-Mook 
  - Domain  : :briefcase: **Business**
  - Priority: :orange_square: **High**
  - Task    : :rocket: **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by T-Mook** [comment]
@tpdud406 

- https://github.com/knowease-inc/MEANIIT-frontend/issues/388 완료되고나면 이 업무부터 진행 요청드립니다~

**Comment by tpdud406** [comment]
## 타 스타트업 고객사 출력 위치 참고

- 원티드 ([회사소개 페이지](https://www.wantedlab.com/) )
   <img width="600" alt="스크린샷 2024-09-26 오후 1 41 33" src="https://github.com/user-attachments/assets/37acf326-600a-4c37-83ee-bd0bcb369219">
- 업스테이지 ([partners 페이지](https://www.upstage.ai/partners/upp?utm_source=upstage.ai&utm_medium=referral&utm_campaign=20240408_footer_Partners_tap_UPP&utm_term=Partners&utm_content=%2Ffooter))
    <img width="600" alt="스크린샷 2024-09-26 오후 1 47 23" src="https://github.com/user-attachments/assets/0eac51ec-c1da-4225-b075-cabf255bf156">
- 아이디어허브 (회사소개 중 [이사회/파트너](https://www.ideahub.co.kr/bbs/content.php?co_id=company&sc=bod_memebers) 페이지)

    <img width="600" alt="스크린샷 2024-09-26 오후 1 49 04" src="https://github.com/user-attachments/assets/59518a86-6e97-416b-b5b0-e9fe93c44581">

- 트웰브랩스 ([홈페이지](https://www.twelvelabs.io/)
   <img width="600" alt="스크린샷 2024-09-26 오후 1 52 44" src="https://github.com/user-attachments/assets/c74fec0b-e827-47d9-a108-691f33dc5947">


## 자사 싸이트 advisor 밑에 고객사 추가할 예정
<img width="1552" alt="스크린샷 2024-09-26 오후 1 55 49" src="https://github.com/user-attachments/assets/19cdea31-abcc-4167-8b2c-b08820c70d50">

**Comment by T-Mook** [comment]
@tpdud406 

- 연혁 위(게타's 서비스 아래)에다가 해주시면 될 것 같습니다!
- CI 넣는 디자인은 업스에티지, 트웰브랩스 등이 나은 것 같네요

**Comment by tpdud406** [comment]
# CI 확보
@T-Mook 
- 다운받는 곳이 없어요(옆 칸에'20주년 엠블렘'은 다운이 있는데..) / 캡처해서 사용해야 할까요..?

## [경기도과학진흥원](https://www.gbsa.or.kr/pages/ci.do)
  <img width="500" alt="스크린샷 2024-09-26 오후 2 22 41" src="https://github.com/user-attachments/assets/2bd55145-18b1-423d-b73e-8ddee0d37279">

## [성균관대학교](https://www.skku.edu/skku/about/symbol/symbol_01.do)
  <img width="359" alt="스크린샷 2024-09-26 오후 2 25 24" src="https://github.com/user-attachments/assets/143180a3-9755-48bb-805b-22314c928abd">

## [차 의과대학교](https://www.cha.ac.kr/%ED%95%99%EA%B5%90%EC%86%8C%EA%B0%9C/%EC%9D%B4%EB%85%90%EA%B3%BC-%EB%B9%84%EC%A0%84/%EB%8C%80%ED%95%99%EC%83%81%EC%A7%95/)
  <img width="299" alt="스크린샷 2024-09-26 오후 2 29 50" src="https://github.com/user-attachments/assets/3af03e2f-0611-4f19-be61-a30fa07f8a85">

## [경민대학교](https://www.kyungmin.ac.kr/homepage/page.do?menu=12)
  <img width="500" alt="스크린샷 2024-09-26 오후 2 08 47" src="https://github.com/user-attachments/assets/250c2f66-a8e0-4a40-98a2-4ac2af0dfa1a">

## [연성대학교](https://www.yeonsung.ac.kr/ko/299/subview.do)
  <img width="500" alt="스크린샷 2024-09-26 오후 2 08 47" src="https://github.com/user-attachments/assets/232af76f-687a-47ae-a5d9-fc2a838e7248">

## [소상공인시장진흥공단](https://www.semas.or.kr/web/ORG01/ORG0105.kmdc)
  <img width="500" alt="스크린샷 2024-09-26 오후 2 08 47" src="https://github.com/user-attachments/assets/82254326-64e3-4ee3-a7ce-f3fdf6287916">

**Comment by T-Mook** [comment]
@tpdud406 

- 100퍼는 아니지만 개발자도구로 열어서 CI 받을수있는지 확인해주세요~

**Comment by T-Mook** [comment]
@tpdud406 

- https://gapchallenge.ai/
- 이 사이트 젤 밑에서 확인 한번해주세요

**Comment by T-Mook** [comment]
@tpdud406 

현재 '게타's 서비스' 미닛의 오른편으로 '교육 서비스'도 넣어주시고 미닛보다는 서브 서비스라는 느낌으로 디자인 살짝 변경해주세요! 서비스 설명은 ai, dx(digital transformation) 교육을 직접 제공한다 정도에서 분량 조절해주시면 됩니다

**Comment by T-Mook** [comment]
@tpdud406 

만약 안되도 제가 공식 ci 오늘내로 받아들일테니 시도만 해봐주심 됩니다

**Comment by T-Mook** [comment]
@tpdud406 

- 로고 메일 확인부탁드립니다~

**Comment by tpdud406** [comment]
@T-Mook 

- 경기도과학진흥원 로고 보내주신걸로 하면 될까요?

### 1. 보내주신 로고 스타일
<img width="1552" alt="스크린샷 2024-09-27 오후 3 06 23" src="https://github.com/user-attachments/assets/f96b8f53-38b7-4436-b613-1c511b67ab33">

### 2. 다른 로고와 배치가 같은 로고 스타일(로고+이름)
<img width="1552" alt="스크린샷 2024-09-27 오후 3 06 32" src="https://github.com/user-attachments/assets/23313276-ca70-4873-92d8-61747ac0c92a">

**Comment by T-Mook** [comment]
@tpdud406 

- 넵 보낸걸로 부탁드리고(배치 같은거 구할수없으면)
- 소상공인건 못 구하면 패스해주세요

**Comment by tpdud406** [comment]
@T-Mook 

- 음.. 배치 같은게 어떤거 말씀하시는거에요~~?


https://github.com/knowease-inc/knowease-inc.github.io/issues/188#issuecomment-2378471007 이 코멘트에 
- 보낸주신랑 CI 다운받은거랑 각각 캡처해놨는데
- 소상공인은 캡처본에 있는 거 사용해도 될까요?

**Comment by tpdud406** [comment]
@T-Mook 
- 고객사 CI 출력 및 보조 서비스 내용 추가했습니다! 확인 부탁드려요~

<img width="1552" alt="스크린샷 2024-09-27 오후 4 54 26" src="https://github.com/user-attachments/assets/a3282e8d-cee0-431d-8dee-37d5b5bba14d">

**Comment by T-Mook** [comment]
@tpdud406 

1. '교육 서비스'도 좌측정렬해주세요
2. '고객사'에서 '게타의 고객사'랑 our partners는 삭제해주셔도됩니다~

**Comment by tpdud406** [comment]
@T-Mook 

- gpt 한테 추천받아 봤습니당..! 
- 저는 1, 2번이 괜찮은것 같은데, 조금 더 적합하고, 마음에 드시는게 있을까요~~?

1. 파트너사 (예시: "파트너 및 협력 기관")
2. 협력 기관 (예시: "협력사 및 기관")
3. 주요 파트너
4. 협력 네트워크
5. 파트너 및 클라이언트

**Comment by T-Mook** [comment]
@tpdud406 

- '고객사 & 협력사'로 일단 해두죠!

**Comment by tpdud406** [comment]
@T-Mook 

- PR 올렸습니다! 확인 부탁드려요~

**Comment by T-Mook** [comment]
- https://github.com/knowease-inc/knowease-inc.github.io/issues/188#issuecomment-2378789603
- 위 내용 반영 안 된것 같은데 확인 부탁드려요~

**Comment by tpdud406** [comment]
@T-Mook 

- 아! 모바일 버전만 말씀하신 줄 알았어요.. 바로 수정했습니다!
- 교육 문구도 수정했습니다~~
