### ISSUE TITLE
고객사 CI 배치 조정 및 불필요한 소제목 삭제

### ISSUE THREAD

**Issue by tpdud406** [knowease-inc/knowease-inc.github.io#190]
# :sparkles: Feature Request

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

- 불필요한 소제목 삭제
- 데스크탑에서만 CI 2줄 ~1줄~ 배치

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 불필요한 소제목 존재
 - CI 일자 나열(모바일은 1줄 유지)

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @tpdud406 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 불필요한 소제목 삭제
  - [x] 고객사 CI 배치 조정

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - #188 , #189
  - 참고문서 URL, 스크린샷 등
    - TBD

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :airplane: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)

  - Reporter: @T-Mook 
  - Domain  : :briefcase: **Business**
  - Priority: :orange_square: **High**
  - Task    : :memo: **Documentation**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by tpdud406** [comment]
@T-Mook 

- 모바일은 원래 중앙 정렬이었는데
- 좌측 정렬로 바꿀까요? 아님 중앙 정렬 유지할까요~~?

<img width="300" alt="스크린샷 2024-10-02 오전 9 18 29" src="https://github.com/user-attachments/assets/717b4d22-9f95-4d22-9dbb-706ae9a3290d">  
<img width="300" alt="스크린샷 2024-10-02 오전 9 18 18" src="https://github.com/user-attachments/assets/eeb91edf-b7bf-49c5-a94f-3c98ae84d1d9">

**Comment by T-Mook** [comment]
@tpdud406 

- 모바일은 중앙정렬 해주시면 됩니다
