### ISSUE TITLE
get-a.io로 접속 시 404 에러 (기존 주소로 접속 시 정상접속)

### ISSUE THREAD

**Issue by T-Mook** [knowease-inc/knowease-inc.github.io#202]
# :lady_beetle: Bug Report

## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

 - https://get-a.io 통한 정상접속 필요

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 배포 실패 에러 해결 이후, 마이그레이션 버전이 배포되자 get-a.io로는 접속되지 않는 에러 발생
 - https://get-a.io로 접속 시 404 에러
 - 기존 주소로 접속 시 정상접속 가능

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

 - @T-Mook 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.

  - [x] 원인파악
  - [x] 문제해결
     - [x] pages creation `public` 체크
     - [x] DNS check 재완료

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우, "#" 혹은 URI 전체를 복사붙여넣기 하는 형태로 **반드시 이슈 번호를 적어주세요**

  - 관련이슈
    - #199, https://github.com/knowease-inc/Business-Strategies/issues/333
  - 참고문서 URL, 스크린샷 등
    - 기존 주소로는 접속됨
      ![화면 캡처 2024-12-30 203436](https://github.com/user-attachments/assets/4ce8d3dd-d17d-4f4e-9e0d-7aea28b85642)
    - get-a.io로는 404에러 발생
      ![화면 캡처 2024-12-30 203412](https://github.com/user-attachments/assets/6145e779-576b-4b22-aa7c-222f38067e17)

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 **한가지만** 선택해주세요.
> (1W- 가 아닌 경우 레이블을 변경해주세요.)

  - 예상소요시간: :airplane: **1W-**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain을 **한가지만** 선택해주세요.
> (UX 가 아닌 경우 Domain 레이블을 변경해주세요.)

  - Reporter: @T-Mook 
  - Task    : :lady_beetle: **Bug**
  - Priority: :red_square: **Emergency**
  - Domain  : :iphone: **UX** 

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.

  - 예상수익: :dollar: (원/월) TBD
  - 예상비용: :money_with_wings: (원/월) TBD

**Comment by T-Mook** [comment]
## 원인파악
1. Pages Creation 설정에서 public 체크가 되어 있지 않은 경우 (아래는 해당 문제를 해결하며 해놓은 상태)
   ![화면 캡처 2024-12-30 205002](https://github.com/user-attachments/assets/65201e6e-3781-4b23-b483-bc4e8634435a)
2. 아래 설정이 빈값으로 존재하게 됩니다
   - public을 풀었다가 다시 public을 체크하여 확인 결과 custom domain 및 DNS 체크 이력이 남아있지 않음 (지금은 입력된 상태)
   - 즉, 이 상태에서 배포가 이루어지는 경우 public을 체크한 다음 다시 DNS 체크 단계까지 이루어져야 하며, 이 사이시간 동안 404 Error로 표시됩니다
     ![화면 캡처 2024-12-30 205148](https://github.com/user-attachments/assets/7d22eeee-9226-4191-988e-4d2209505005)
3. 배포가 이루어질 때, 미리 해당 부분을 체크 및 입력한 다음 배포가 이루어지거나, 잦은 배포가 예상되는 시기에는 public을 체크해두었다가, 닫는 형태로 관리할 수 있을 것으로 보입니다.

@tooget public 상태일 때의 위험이 위협적이지 않다면 public으로 유지해두는 것도 선택지로 둘 수 있는지 궁금한데, 어떻게 생각하시나요?

**Comment by tooget** [comment]
## 문제와 Trade-off 정리
### 문제(?): Github Organization의 Pages Creation 'Public' 권한을 부여한 상태(체크상태)이지 않으면, knowease-inc.github.io 의 Github Actions 배포 후 Custom Domain 설정이 비어있게 된다?
 - 상식적으로 납득하기 어려운 문제?: 'Page Creation' 권한 설정 변경이, 이미 만들어진 Github Pages 리포지토리 커스텀 도메인 설정에 영향을 미친다?

### Trade-off
| 항목 | 가치 | 가치판단 |
| -- | -- | -- |
| 빈 커스텀 도메인 설정을 다시 입력할 경우, DNS 인증에 시간이 걸린다 | **DNS 인증 지연** | Bad |
| 'Public' 권한을 체크해 둔 상태라면, Owner가 아닌 Github 조직 내 멤버가 처음부터 인터넷에 공개되는 상태로 리포지토리를 생성할 수 있다. | **잠재적 코드유출** | Bad |

#### 문제상황 정리 중

|`www.get-a.io` -> knowease-inc.github.io: Github Pages Custom Domain 설정 | [ ] [커스텀 도메인 공식문서](https://docs.github.com/ko/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) 와 같은 DNS 레코드가 세팅되어 있는지? |
![image](https://github.com/user-attachments/assets/b48416c5-a57c-465a-a873-688f254a6455)
| https://github.com/orgs/community/discussions/48422 : 배포를 새로 할 때마다 CNAME 파일이 깨끗해지는 문제?(=커스텀 도메인 ALIAS가 작동하지 않는 문제) | [ ] 이 문제 혹은 [유사한 케이스 등](https://stackoverflow.com/questions/67183664/why-is-my-github-pages-custom-domain-constantly-reset) 에 해당되지는 않는지? |

### 소결
 - 'Public' 권한을 계속 부여한 상태는 좋지 않아 보입니다. ([Github Enterprise 더 비싼 구독플랜에 Private만 만들수 있는 권한제한 기능이 있는 것에 비추어 볼 때 실수에 의한 보안위협 추론 가능](https://docs.github.com/en/organizations/managing-organization-settings/restricting-repository-creation-in-your-organization)
 - 단기적으로는, 말씀하신 대로 배포가 빈번한 시기에 체크를 넣은 상태로 진행하고, 수정이 끝나면 권한을 해제하는 것이 좋아 보입니다.
 - 중장기적으로는, 문제 자체를 해결할 수도 있어 보이니 이를 별도 이슈로 해결하는 게 좋을 것 같습니다. 좀 더 찾아보겠습니다.


@T-Mook

**Comment by T-Mook** [comment]
@tooget 

- 역시 유료 기능 관련이라 불편하게 방치인가 싶긴해지네요ㅋㅋ

**Comment by tooget** [comment]
@T-Mook 

넵, SaaS의 전형적인 비지니스 모델이지요 ㅎㅎ;
 - 본서비스(저렴) + IdP통합/세부권한 관리기능(비쌈:큰규모 사업체용)

**Comment by T-Mook** [comment]
@tooget 

- 우선은 제가 public 온오프 잘 관리해볼게요ㅋ
- 아니면 이 repo PR 이슈에만 체크리스트(?)처럼 최소한 인지는 하게 해도 될듯하네요

**Comment by T-Mook** [comment]
# 이슈 close
- 사유: 문제는 해결되었습니다!
