### ISSUE TITLE
EASYXPLAIN 서비스 사용자의 문제해결, 불편사항, 개선의견 등 소통 창구 (Customer Support 페이지) 구현

### ISSUE THREAD

**Issue by tooget** [knowease-inc/knowease-inc.github.io#44]
## 이런 목표를 달성해야 합니다
> 이 이슈로 무슨 목표를 달성하고자 하며 어떤 상태가 되어야 하는지 간결히 적어주세요.

EASYXPLAIN 서비스 사용자의 문제해결, 불편사항, 개선의견 등 소통 창구를 마련하여야 합니다.

## 현재 이런 상태입니다
> 이 이슈를 생성한 현시점의 문제 혹은 향후 문제 발생 가능성에 대하여 간결히 적어주세요.

 - 2021-08-23일 현재, EASYXPLAIN 서비스에 대한 사용자 문제해결, 불편사항, 개선의견을 위한 소통창구가 존재하지 않습니다.
 - 2021-08-23일 현재, 향후 서비스 확장에 따른 사용자와의 소통 창구 오퍼레이션 프로세스가 존재하지 않습니다.

## 이 이슈는 이 분이 풀 수 있을 것 같습니다
> 담당할 Assignee를 @로 **1명만** 멘션해주세요.

@tooget 

## 아래의 세부적인 문제를 풀어야 할 것 같습니다
> 이 이슈를 해결하기 위한 세부 항목(이슈 클로징 조건)을 체크리스트로 적어주세요.
  - [x] UX: 유저 입장에서 제안/문의내용 전송 구현
    - [x] Github Pages EASYXPLAIN 서비스 설명 페이지 > 입력 폼 내용 입력 > Submit
    - [x] 생성 완료 메시지
  - [ ] 오퍼레이션
    - [ ] Github Issue 생성시 Github Actions, 기타 3rd-party 등으로부터 트리거 → 알림 등 오퍼레이션 설계
    - [ ] 향후 Zendesk 등 CRM 관리 확장(안) 검토

## 이 이슈를 해결하기 위해 이런 내용을 참고할 수 있을 것 같습니다
> 문제 해결에 도움이 될 수 있을 것 같은 관련 이슈 번호, 문서, Wiki, 스크린샷, 개인적인 의견 등을 최대한 적어주세요.
> 이 이슈가 다른 이슈와 관련되어 있는 경우는 **반드시 이슈 번호를 적어주세요**
  - 관련이슈: https://github.com/knowease-inc/EASYXPLAIN/issues/170
  - 참고사항
    - 적용대상: https://staticman.net/

## 이 이슈 해결을 위해 이정도 시간이 예상됩니다
> 예상소요시간을 한가지만 선택해주세요.
> (1W+ 가 아닌 경우 레이블을 변경해주세요.)
  - 예상소요시간: **1W+**

## 관련된 세부 정보입니다.
> Reporter는 **1명만**, Domain, Priority, Task를 **각각 한가지만** 선택해주세요.
> (UX, Medium, Enhancement 가 아닌 경우 레이블을 변경해주세요.)
  - Reporter: @tooget 
  - Domain  : **UX**
  - Priority: **High**
  - Task    : **Enhancement**

## 이 이슈를 해결함에 따라 이정도 재무적 영향이 예상됩니다.
> 이 이슈를 해결함에 따라 전사적으로 유의미한 수익/비용 변동이 예상될 경우, 해당 수치를 입력해주세요.
  - 예상수익: 0 원/월
  - 예상비용: 0 원/월

**Comment by tooget** [comment]
@T-Mook 

 - 기본적인 컴포넌트 및 API 호출에 필요한 기본적인 스크립트는 전부 넣었습니다.
 - Typescript 및 AXIOS 세팅이 되어 있지 않아 현재 동작하지 않습니다. 도움!

**Comment by tooget** [comment]
@T-Mook 

 - Typescript 및 AXIOS 세팅이 되어 있지 않아 현재 동작하지 않습니다. (잘 모르겠습니다.. 도움 주실 수 있으실까요!)
 - 화면상 컴포넌트 및 API 호출에 필요한 스크립트는 모두 커밋하였습니다.

**Comment by T-Mook** [comment]
@tooget 정신 좀 드는데로 출근해서 보겠습니다 :)

**Comment by T-Mook** [comment]
## Assigness 변경
* @tooget  -> @T-Mook 
* 사유 : 기능 구현 종료 후 UI 마무리

**Comment by tooget** [comment]
@T-Mook @tooget 

## 구현 논의 결과
 - 스캐폴딩 및 다중 서비스인 경우의 통합 방향
   - /components/pages.service.easyxplain.voiceofcustomer 로 함
   - 다중 서비스 간 Customer Journey/고객 티켓 통합은 추후 별도 고려
   - /pages/service/easyxplain/voiceofcustomer.vue 페이지 분리
     - 해당 페이지 동선은 서비스 내에서만 접근하도록, 소개 페이지 메뉴상에서 표현하지 않음
 - 티켓 라이프사이클
   - 이메일 주소 입력 필수
     - 사용자 단방향 커뮤니케이션이 아닌, 서비스 User Story상 사용자와의 인터랙션이 필수적임
     - 최소한의 연락처를 받을 필요가 있음
   - 연락이 되지 않는 경우, 서비스 운영 멤버의 문제 대응 및 해결 판단 & 14일 이내 사용자 메일 상 응답이 없다면 클로즈(안)
     - 참고: 민법 발신주의
